version: '3'

services:
  app:
    image: app
    build:
      context: start/
      args:
        TIMEZONE: Asia/Taipei
    container_name: app
    environment:
        LANG: C.UTF-8
    ports:
      - "666:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pa55w0rd
      MYSQL_DATABASE: testing
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
       - "6379:6379"

volumes:
  mysql-data:
  redis_data:
